### PR TITLE
Made it possible to use ArrayBuffer if available.

### PR DESCRIPTION
**Pull request by FlatAssembler**
I modified the "compiler.html" file a bit, to use the features of newer browsers if they are available.
By the way, I know the "compiler.html" file is somewhat poorly written. If you have trouble understanding some part of it, feel free to ask.

### CODE REVIEW

**Comment by FlatAssembler** [comment]
Also, @dragitz, I think it would now be relatively easy to make a NodeJS version which is just as powerful as the Duktape version. Do you think that would be a good idea? I think it would be, especially for Linux users. Few distributions have Duktape package, while almost all have reasonably modern NodeJS package.
I also think it would be a good idea to make it target GAS as well as FlatAssembler, for which we can use the algorithms used in those programs: [convert.c](https://raw.githubusercontent.com/FlatAssembler/SimpleCalculator/master/convert.c) and [prepare_for_gcc.c](https://raw.githubusercontent.com/FlatAssembler/SimpleCalculator/master/prepare_for_gcc.c).

**Comment by FlatAssembler** [comment]
So, @dragitz you are no longer interested in working with me, or?

**Comment by FlatAssembler** [comment]
Anyway, I've implemented the first ternary operator in AEC (the operator '?:'). Maybe that will help you with implementing dot product.

**Comment by FlatAssembler** [comment]
Anyway, I've prettified the code using Prettier, I hope you like it.

**Comment by FlatAssembler** [comment]
Did you know those "st1,st0" after FPU directives aren't necessary in most cases in FASM? Just made the compiler use them only when necessary.

**Comment by FlatAssembler** [comment]
So, I modified "months.aec" to be both an example of ElseIf and of the ternary operator.

**Comment by FlatAssembler** [comment]
Do you have some idea what is to be done about [this](https://github.com/FlatAssembler/ArithmeticExpressionCompiler/issues/1)? I mean, the algorithm in [compiler.js](https://github.com/FlatAssembler/ArithmeticExpressionCompiler/blob/master/control.js) is fundamentally flawed, and I don't have much time to think of a new one and implement it.

**Comment by FlatAssembler** [comment]
I've made a dirty fix to control.js so that qsort.aec compiles. Nevertheless, the underlying issue remains unsolved.

**Comment by FlatAssembler** [comment]
The assembly that the compiler now produces is a bit more legible now, I think you will like that.

**Comment by FlatAssembler** [comment]
I've improved syntax highlighting script for Notepad++. Do you maybe know how to write syntax highlighting scripts for other commonly used editors? Such as VSCode, VIM, Atom...? Notepad++ is probably the easiest one.

**Comment by FlatAssembler** [comment]
I've changed the example expression to make it obvious we are using the parsing of the ternary operator that's compatible with C (https://stackoverflow.com/questions/62099786/how-is-the-conditional-operator-parsed). I've also fixed a CSS error. JavaScript is unchanged.

**Comment by FlatAssembler** [comment]
I've made a NodeJS- and GAS-compatible version, it's available as a release.

**Comment by FlatAssembler** [comment]
I've included 32-bit Linux executables in the ZIP, so that some less-tech-savvy Linux users don't have to bother compiling Duktape from source.

**Comment by FlatAssembler** [comment]
I don't have plans for what I'll do next. If you have trouble with me and you working at the same time, I'll stop working on the project now.

**Comment by FlatAssembler** [comment]
I've included another example for Linux in the ZIP, so that Linux users don't feel disadvantaged. Which OS are you using, @dragitz ? Are you still interested in working with me? If not, why?

**Comment by FlatAssembler** [comment]
I've added an example program for DOS there. By the way, @dragitz would you know how to compile Duktape to run on DOS? I think that's feasible, but I myself don't know how to do that. Also, do you think it's possible to port the Analog Clock program to run on bare metal, like it runs on Linux and DOS now? I also think that's feasible, but I am not sure. You claim to be an expert in Assembly, so I suppose you'd know that.

**Comment by dragitz** [comment]
I have never claimed to be an expert in Assembly

**Pull request merged**
