### PR TITLE
I've refactored some AEC programs

### PR DESCRIPTION
**Pull request by FlatAssembler**
Hey, @dragitz !
I've just wanted to notify you that I've refactored some AEC programs to make them easier to read, specifically, the "permutations.aec" and "PascalTriangle.aec", both in the "ArithmeticExpresionCompiler.zip" archive.
Out of curiosity, what are you planning to do with ArithmeticExpressionCompiler? What do you like about it?

### CODE REVIEW

**Comment by dragitz** [comment]
Hi thanks for reaching, I have no big plans besides adding a few functions like dot product.

I really like this tool because it allows me to do complex calculations, really useful!

**Comment by FlatAssembler** [comment]
Dot product? Well, thank you if you know how to do that! I have no idea how to implement 2-dimensional arrays, yet alone something more.

**Comment by dragitz** [comment]
I mean, this is it.

```
finit
fld dword [aX]
fld dword [bX]
fmulp st(1),st(0)
fld dword [aY]
fld dword [bY]
fmulp st(1),st(0)
faddp st(1),st(0)
fld dword [aZ]
fld dword [bZ]
fmulp st(1),st(0)
faddp st(1),st(0)
fstp dword [DotProduct]
```

**Comment by FlatAssembler** [comment]
And where would you put that in the code? The parser currently supports only one-argument and two-argument (two-argument functions having to be hard-coded into it) functions. So, you can't easily add a 6-argument function into the language right now. I mean, by all means, try to! I'll be thankful if you manage to do that.

**Comment by dragitz** [comment]
I'll see what I can do, no promises though!

**Comment by FlatAssembler** [comment]
Well, the fact that somebody is willing to work on my programs already means much to me!

**Pull request merged**
